[settings]
# toggles discoverability at time of deployment
deploy = true
# true if challenge needs containers hosted
containers = false
# health_check = false

# ============================================================
# NOTE: the following is only necessary if workspace.toml
#   defines a scoring-type of static for ctfd
# This can be safely removed
# ============================================================

[ctfd]
points = 500
